<Project Sdk="Microsoft.NET.Sdk">

    <PropertyGroup>
        <RootNamespace>TestApp.VB</RootNamespace>
        <TargetFramework>net8.0</TargetFramework>
    </PropertyGroup>

    <ItemGroup>
      <ProjectReference Include="..\VBBlazor.Runtime\VBBlazor.Runtime.vbproj" />
    </ItemGroup>

</Project>
